import { chromium } from 'playwright';
import { seedDemo } from './seed-demo.mjs';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { PlanStore } from '../plugins/progress-target/core/storage.js';
import { PlanService } from '../plugins/progress-target/core/operations.js';
import { createDashboard } from '../plugins/progress-target/server/dashboard.js';
import { planArgs, execution, iso } from '../tests/fixtures.mjs';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const qa = join(root, 'qa');
await mkdir(join(qa, 'test-runs'), { recursive: true });
const testHome = await mkdtemp(join(qa, 'test-runs/browser-'));
await mkdir(join(testHome, 'browser-temp'));
process.env.TEMP = join(testHome, 'browser-temp');
process.env.TMP = process.env.TEMP;
const browser = await chromium.launch({ headless: true, channel: process.env.PT_BROWSER_CHANNEL || 'chrome' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1080 }, locale: 'zh-CN', timezoneId: 'Asia/Shanghai' });
const page = await context.newPage();
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const threadId = 'browser-showcase-thread';
const showcaseId = 'browser-showcase-plan';
const check = label => checks.push({ label, passed: true });
const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), '页面不应横向溢出');
let isolatedServer, showcaseServer;
try {
  const showcaseHome = join(testHome, 'showcase');
  await seedDemo(showcaseHome);
  const showcaseStore = new PlanStore(join(showcaseHome, 'runtime/data'));
  await new PlanService(showcaseStore).create({ ...planArgs(showcaseHome, Date.now(), 1), threadId, planId: showcaseId, title: '界面检查 · 合成计划' });
  showcaseServer = await createDashboard({ dataDir: showcaseStore.root, runtimeDir: showcaseHome, projectHome: root, port: 0 }, { writeState: false });
  const base = showcaseServer.url;
  await page.goto(base + '/');
  await page.getByRole('heading', { name: '从当前 Codex 对话打开计划', exact: true }).waitFor();
  assert.equal(await page.locator('[data-plan]').count(), 0);
  check('无对话身份的入口不列出任何真实计划');
  await page.goto(base + '/?thread=' + encodeURIComponent(threadId) + '&plan=' + showcaseId);
  await page.getByRole('heading', { name: '界面检查 · 合成计划', exact: true }).waitFor();
  await page.getByText('已连接 · 自动更新', { exact: true }).waitFor();
  check('隔离测试计划可见，实时连接已建立');
  await noOverflow();
  await page.screenshot({ path: join(qa, 'dashboard-project.png'), fullPage: true });
  assert.equal(await page.locator('[data-plan="demo-research"]').count(), 0);
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: base });
  await page.getByRole('button', { name: '复制链接 ↗' }).click();
  await page.getByRole('status').filter({ hasText: '看板链接已复制' }).waitFor();
  const ownLink = new URL(await page.evaluate(() => navigator.clipboard.readText()));
  assert.equal(ownLink.searchParams.get('thread'), threadId);
  assert.equal(ownLink.searchParams.get('plan'), showcaseId);
  const exportUrl = new URL(await page.getByRole('link', { name: '导出计划 ↓' }).getAttribute('href'), base);
  assert.equal(exportUrl.searchParams.get('thread'), threadId);
  check('当前计划的复制和导出链接保留对话归属，演示数据不混入');
  await page.goto(base + '/?demo=1');
  await page.locator('.demo-banner').waitFor();
  await page.getByRole('searchbox', { name: '搜索任务' }).fill('推荐模型');
  assert.equal(await page.locator('[data-plan]').count(), 1);
  await page.locator('[data-plan="demo-research"]').click();
  await page.locator('.demo-banner').waitFor();
  assert.equal(await page.getByRole('heading', { name: '推荐模型实验 · 质量与交付', exact: true }).count(), 1);
  check('演示需要显式入口，搜索与选择只包含演示数据');
  await page.getByRole('searchbox', { name: '搜索任务' }).fill('');
  await page.locator('[data-phase="train-baseline"]').click();
  assert.match(await page.locator('#detail').innerText(), /0\.247/);
  assert.match(await page.locator('#detail').innerText(), /逾期交付/);
  check('阶段切换与未达标逾期交付展示');
  await page.getByRole('tab', { name: '资源', exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), /资源快照/);
  await page.getByRole('tab', { name: '活动', exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), /活动记录/);
  await page.getByRole('tab', { name: '验收', exact: true }).click();
  await page.getByText('指标依据与最终目标关联', { exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), /界面演示数据说明/);
  check('验收、资源、活动标签及依据展开');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: '导出计划 ↓' }).click();
  const download = await downloadPromise;
  await download.saveAs(join(testHome, 'exported-plan.json'));
  check('通过页面下载计划 JSON');
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: base });
  await page.getByRole('button', { name: '复制链接 ↗' }).click();
  await page.getByRole('status').filter({ hasText: '看板链接已复制' }).waitFor();
  const demoLink = new URL(await page.evaluate(() => navigator.clipboard.readText()));
  assert.equal(demoLink.searchParams.get('demo'), '1');
  assert.equal(demoLink.searchParams.get('plan'), 'demo-research');
  check('复制选中任务的查看链接');
  await page.getByRole('status').filter({ hasText: '看板链接已复制' }).waitFor({ state: 'hidden' });
  await page.locator('[data-phase="full-evaluation"]').click();
  await page.screenshot({ path: join(qa, 'dashboard-demo.png'), fullPage: true });
  for (const width of [1024, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await noOverflow();
    await page.screenshot({ path: join(qa, 'dashboard-' + width + '.png'), fullPage: true });
  }
  check('桌面、平板、手机宽度下无横向溢出');

  // Real browser observes a write by a separate service instance, without a reload.
  const store = new PlanStore(join(testHome, 'data'));
  const service = new PlanService(store);
  const args = { ...planArgs(testHome, Date.now(), 1), threadId: 'browser-a', title: '对话 A 的独立计划' };
  delete args.executionState;
  args.timeline[0].metrics[0].value = null;
  args.timeline[0].executionPlan.resourceDiscovery = { deferred: true, reason: '等待明确执行后查询' };
  const plan = await service.create(args);
  const other = await service.create({ ...args, threadId: 'browser-b', title: '对话 B 的独立计划' });
  isolatedServer = await createDashboard({ dataDir: store.root, runtimeDir: testHome, projectHome: root, port: 0 }, { writeState: false });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.goto(isolatedServer.url + '/?thread=browser-a');
  await page.locator('[data-phase="phase-1"]').waitFor();
  assert.equal(await page.locator('[data-plan]').count(), 1);
  assert.equal(await page.locator('[data-plan="' + other.id + '"]').count(), 0);
  assert.match(await page.locator('#detail').innerText(), /尚未测量/);
  await page.getByRole('tab', { name: '资源', exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), /待执行前查询/);
  check('同目录对话 A 只显示 A 的计划，未测量和待查询状态真实展示');
  await service.updatePhase({ planId: plan.id, expectedRevision: plan.revision, phaseId: 'phase-1', patch: { progress: 37 } });
  await page.locator('[data-phase="phase-1"] .phase-status strong').filter({ hasText: '37%' }).waitFor();
  check('独立写入后页面通过 SSE 自动更新，无刷新操作');
  await page.goto(isolatedServer.url + '/?thread=browser-b');
  await page.getByRole('heading', { name: '对话 B 的独立计划', exact: true }).waitFor();
  assert.equal(await page.locator('[data-plan]').count(), 1);
  assert.equal(await page.locator('[data-plan="' + plan.id + '"]').count(), 0);
  check('对话 B 的入口不会显示或选中 A 的计划');
  await page.goto(isolatedServer.url + '/?thread=browser-c');
  await page.getByRole('heading', { name: '当前对话还没有计划', exact: true }).waitFor();
  assert.equal(await page.locator('[data-plan]').count(), 0);
  await page.screenshot({ path: join(qa, 'dashboard-empty-thread.png'), fullPage: true });
  check('未建计划的新对话保持为空，不自动继承同目录计划');
  const brokenPath = store.path('broken-independent-plan');
  await writeFile(brokenPath, '{broken');
  await page.goto(isolatedServer.url + '/?thread=browser-b');
  await page.getByRole('heading', { name: '对话 B 的独立计划', exact: true }).waitFor();
  await page.locator('#error').filter({ hasText: '列表可能不完整' }).waitFor();
  assert.equal(await page.locator('[data-plan]').count(), 1);
  assert.equal(await readFile(brokenPath, 'utf8'), '{broken');
  await page.screenshot({ path: join(qa, 'dashboard-recovery.png'), fullPage: true });
  check('其他计划损坏时仍显示本对话计划，并提示列表可能不完整且保留原文件');
  await writeFile(brokenPath, JSON.stringify({ ...other, id: 'broken-independent-plan', ownerThreadId: 'repaired-isolated-thread' }));
  await page.locator('#refresh').click();
  await page.locator('#error').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('[data-plan]').count(), 1);
  check('状态文件恢复后警告自动清除，恢复的数据仍按对话隔离');
  const oldPhase = {
    ...args.timeline[0], id: 'legacy-phase', pLabel: 'P-旧', timeline: '依照原来的分片和时间安排',
    status: 'in-progress', startedAt: iso(Date.now() - 2 * 3600000), deadlineAt: iso(Date.now() - 60000), deadlineBreached: true,
    metrics: [{ key: '旧质量指标', value: 50, operator: '>=', targetValue: 100, unit: '%' }],
    deliverables: [{ name: '必需旧产物', required: true, status: 'ready', acceptance: '可被下游使用', evidence: 'fixture://legacy-output' }, { name: '可选附录', required: false, status: 'pending', acceptance: '仅需时提供', evidence: '' }],
    executionPlan: { ...execution(Date.now() - 2 * 3600000), checkpoints: [{ kind: '5min', minutes: 5 }, { kind: '50%', minutes: 10 }, { kind: '75%', minutes: 15 }], harvestAtMinutes: 20 },
  };
  delete oldPhase.metricResearch; delete oldPhase.objectiveContribution;
  const imported = await service.importPlan({ threadId: 'browser-legacy', workspaceRoot: testHome, userAuthorized: true, reason: '验证旧 DSH 页面字段', plan: { title: '旧计划展示检查', introduction: '原版完整计划说明与巡检约定', timeline: [oldPhase] } });
  await page.goto(isolatedServer.url + '/?thread=browser-legacy');
  await page.getByRole('heading', { name: '旧计划展示检查', exact: true }).waitFor();
  await page.locator('.plan-introduction summary').click();
  assert.match(await page.locator('.plan-introduction').innerText(), /原版完整计划说明与巡检约定/);
  assert.match(await page.locator('#detail').innerText(), /P-旧/);
  assert.match(await page.locator('#detail').innerText(), /依照原来的分片和时间安排/);
  assert.match(await page.locator('#app').innerText(), /v1 兼容模式/);
  check('原 DSH 的计划说明、阶段标签、文字时间安排与 v1 兼容提示均可见');
  assert.match(await page.locator('#detail').innerText(), /逾期执行中/);
  assert.match(await page.locator('[data-phase="legacy-phase"]').innerText(), /逾期执行中/);
  assert.match(await page.locator('#detail').innerText(), /交付物门通过/);
  assert.match(await page.locator('#detail').innerText(), /1 \/ 1 必需项已就绪/);
  assert.match(await page.locator('#detail').innerText(), /可选/);
  check('逾期执行中区别于已逾期交付，交付物门只计算必需项');
  await page.getByRole('tab', { name: '资源', exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), /结果收获点 · 20 分钟/);
  assert.match(await page.locator('#detail').innerText(), /不可分片/);
  await page.getByRole('tab', { name: '活动', exact: true }).click();
  assert.match(await page.locator('#detail').innerText(), new RegExp(new Date().getFullYear().toString()));
  assert.equal(await page.locator('.plan-introduction').evaluate(element => element.open), true);
  check('旧格式单独 harvestAtMinutes 仍显示收获点，完整时间包含年份');
  await page.screenshot({ path: join(qa, 'dashboard-legacy.png'), fullPage: true });
  const incomplete = { ...oldPhase, status: 'completed', completedAt: iso(Date.now() - 30000), metrics: [] };
  await service.importPlan({ threadId: 'browser-legacy-empty', workspaceRoot: testHome, userAuthorized: true, reason: '验证缺指标的历史展示', plan: { title: '缺少历史指标', timeline: [incomplete] } });
  await page.goto(isolatedServer.url + '/?thread=browser-legacy-empty');
  await page.getByRole('heading', { name: '缺少历史指标', exact: true }).waitFor();
  assert.match(await page.locator('#detail').innerText(), /历史阶段已结束，但未记录结构化质量指标/);
  check('已结束但缺指标的旧记录明确提示，不能误认质量达标');
  await page.route('**/api/events?**', route => route.abort());
  await page.goto(isolatedServer.url + '/?thread=browser-a');
  await page.getByRole('heading', { name: '对话 A 的独立计划', exact: true }).waitFor();
  let latest = await store.read(plan.id);
  latest = await service.manage({ operation: 'revise-plan', threadId: 'browser-a', planId: latest.id, expectedRevision: latest.revision, title: '断线后由本地读取恢复' });
  await page.getByRole('heading', { name: '断线后由本地读取恢复', exact: true }).waitFor({ timeout: 16000 });
  check('SSE 连接不可用时，本地 10 秒读取仍更新进度，不调用模型');
  await service.manage({ operation: 'delete-plan', threadId: 'browser-a', planId: latest.id, expectedRevision: latest.revision, userAuthorized: true, reason: '删除隔离浏览器测试计划' });
  await page.getByRole('heading', { name: '当前对话还没有计划', exact: true }).waitFor({ timeout: 16000 });
  assert.equal(await page.locator('[data-plan]').count(), 0);
  check('删除当前计划后恢复空白状态，不残留旧计划或选用其他对话');
  assert.deepEqual(errors, []);
  check('全部页面交互无 JavaScript 异常');
  await writeFile(join(qa, 'ui-verification.json'), JSON.stringify({ at: new Date().toISOString(), browser: 'Chromium/' + browser.version(), checks, pageErrors: errors }, null, 2) + '\n');
  console.log(JSON.stringify({ passed: checks.length, screenshots: ['dashboard-project.png', 'dashboard-demo.png', 'dashboard-1024.png', 'dashboard-390.png'] }));
} finally {
  await context.close();
  await browser.close();
  await isolatedServer?.close();
  await showcaseServer?.close();
}
